project:
  type: website
  output-dir: docs



website:
  title: "Jared Kalow"
  site-url: https://jaredskalow.github.io/
  description: "Jared Kalow is a PhD Candidate in Political Science at MIT studying comparative political behavior, urban politics, and ethnic politics in the Global South."
  google-analytics:
    tracking-id: "G-CXVJKMW1ND"
    anonymize-ip: true

  navbar:
    left:
      - href: index.md
        text: Home

format:
  html:
    theme: none
    css: style.css
    toc: true
    include-in-header:
      text: |
        <!-- Privacy-friendly analytics by Plausible -->
        <script async src="https://plausible.io/js/pa-FQ2JrqDRleyy8hCry1VNW.js"></script>
        <script>
          window.plausible=window.plausible||function(){(plausible.q=plausible.q||[]).push(arguments)},plausible.init=plausible.init||function(i){plausible.o=i||{}};
          plausible.init()
        </script>

    

editor: visual



